more verbose torch installation

diff --git a/.github/workflows/pytests.yml b/.github/workflows/pytests.yml
--- a/.github/workflows/pytests.yml
+++ b/.github/workflows/pytests.yml
@@ -62,6 +62,36 @@ jobs:
           sudo apt install intel-oneapi-mkl
           sudo apt install intel-oneapi-mkl-devel
 
+      - name: MACE
+        run: |
+          echo "search for torch version"
+          set +o pipefail
+          # search for available torch version with +cpu support
+          for torch_version_test in $( python3 -m pip install torch== 2>&1 | fgrep 'from versions' | 
+                                       sed -e 's/.*from versions: //' -e 's/)//' -e 's/,[ ]*/\n/g' | tac ); do
+              set +e
+              echo "torch version, $torch_version_test"
+              python3 -m pip install --dry-run torch==${torch_version_test}+cpu \
+                                     -f https://download.pytorch.org/whl/torch_stable.html
+              search_stat=$?
+              set -e
+              if [ $search_stat == 0 ]; then
+                  torch_version=${torch_version_test}
+                  break
+              fi
+          done
+          if [ -z $torch_version ]; then
+              echo "Failed to find any pytorch version with +cpu variant" 1>&2
+              exit 1
+          fi
+          echo "found torch version ${torch_version}+cpu, installing"
+          python3 -m pip install torch==${torch_version}+cpu -f https://download.pytorch.org/whl/torch_stable.html
+          echo "installing mace"
+          python3 -m pip install git+https://github.com/ACEsuit/mace.git@main
+          python3 -c "import mace; print(mace.__file__)"
+
+
+
       - name: Install phono3py from source
         run: |
             # find mklvars
@@ -100,33 +130,6 @@ jobs:
           python3 -m pip install typing-extensions
           # install pandas now to encourage compatible numpy version after conda regressed it
           python3 -m pip install pandas
-
-      - name: MACE
-        run: |
-          echo "search for torch version"
-          set +o pipefail
-          # search for available torch version with +cpu support
-          for torch_version_test in $( python3 -m pip install torch== 2>&1 | fgrep 'from versions' | 
-                                       sed -e 's/.*from versions: //' -e 's/)//' -e 's/,[ ]*/\n/g' | tac ); do
-              set +e
-              python3 -m pip install --dry-run torch==${torch_version_test}+cpu \
-                                     -f https://download.pytorch.org/whl/torch_stable.html > /dev/null 2>&1
-              search_stat=$?
-              set -e
-              if [ $search_stat == 0 ]; then
-                  torch_version=${torch_version_test}
-                  break
-              fi
-          done
-          if [ -z $torch_version ]; then
-              echo "Failed to find any pytorch version with +cpu variant" 1>&2
-              exit 1
-          fi
-          echo "found torch version ${torch_version}+cpu, installing"
-          python3 -m pip install torch==${torch_version}+cpu -f https://download.pytorch.org/whl/torch_stable.html
-          echo "installing mace"
-          python3 -m pip install git+https://github.com/ACEsuit/mace.git@main
-          python3 -c "import mace; print(mace.__file__)"
 
       - name: Julia and ace fit
         run: |
